# Woodpecker Pipeline configuration for Astro & Bun
# Triggers only when pushing to your main branch
when:
  branch: main
  event: push

steps:
  build-project:
    image: oven/bun:latest
    environment:
      DEPLOY_TARGET: codeberg
    commands:
      - bun install --frozen-lockfile
      - bun run build

  deploy-pages:
    image: alpine/git:latest
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - cd dist

      # See https://codeberg.org/forgejo/forgejo/issues/2809
      - AUTH_STR="$CI_REPO_OWNER:$CODEBERG_TOKEN"
      - AUTH_TOKEN=$(echo -n "$AUTH_STR" | base64 | tr -d '\n')
      #
      - git config --global user.email "woodpecker-ci@noreply.codeberg.org"
      - git config --global user.name "Woodpecker CI"
      #
      - git init -b main
      - git add .
      - 'git commit -m "ci: production deploy via woodpecker [skip ci]" --allow-empty'
      #
      - git remote add origin https://codeberg.org/$CI_REPO.git
      - 'git -c http.extraHeader="Authorization: Basic $AUTH_TOKEN" push --force origin main:pages'
